// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Timer(Props) {
  return React.createElement("div", undefined, "One day this will be a timer");
}

var make = Timer;

exports.make = make;
/* react Not a pure module */
